### PR TITLE
Fix LateInitializationError: Local `firstIndex` has not been initialized

### LINKED ISSUE #151: bug(null-safety): LateInitializationError: Local `firstIndex` has not been initialized.
If neither the `if` nor `else if` triggers to initialize the `firstIndex`, then this code will fail as it remains uninitialized:
https://github.com/letsar/flutter_staggered_grid_view/blob/3b835ed313b6f4145d1520b48debea62f72f3a56/lib/src/widgets/sliver.dart#L124-L133

### PR DESCRIPTION
**Pull request by aarontwf**
Fixes #151

### CODE REVIEW

**Comment by acoutts** [comment]
Any update getting this merged?

**Comment by acoutts** [comment]
Actually, @aarontwf I am still getting the same exception with your PR.

**Comment by acoutts** [comment]
Nevermind! Works like a charm 👍

**Comment by letsar** [comment]
Thank you very much for this PR

**Pull request merged**
