### PR TITLE
optimize node cache strategy

### PR DESCRIPTION
**Pull request by bladeofgod**
feature:
1.expose addAutomaticKeepAlives
2.add forceKeepChildWidget for control childWidgets's clear time. and reuse child widget
3.optimize node cache strategy. now ,we can set keepBucket's size by keepBucketSize, to avoid big memory usage.

test data:
https://github.com/letsar/flutter_staggered_grid_view/pull/190#issuecomment-877930316

### CODE REVIEW

**Comment by Tom3652** [comment]
Thank you for your great work but how can i use your fork please ?

**Comment by bladeofgod** [comment]
> Thank you for your great work but how can i use your fork please ?

here is my pr link:
https://github.com/bladeofgod/flutter_staggered_grid_view

**Comment by Tom3652** [comment]
thank you ! the keepBucketSize is in MB ?

**Comment by bladeofgod** [comment]
> thank you ! the keepBucketSize is in MB ?

is number, represents  the number of nodes(renderObject) that are not in the screen.

**Comment by rmControls** [comment]
@letsar can you merge this please......

**Comment by letsar** [comment]
Closing as it resolved or will not be fixed in the current version (a new version, completely refactored is on its way).
Let me know If you can test under the feature/renaissance branch, and it's not resolved.

**Comment by bladeofgod** [comment]
> Closing as it resolved or will not be fixed in the current version (a new version, completely refactored is on its way). Let me know If you can test under the feature/renaissance branch, and it's not resolved.

nice!   i will run it later. :)

**Pull request closed without merging**
