### PR TITLE
optimize node cache strategy, 

### PR DESCRIPTION
**Pull request by bladeofgod**
feature:
1. expose addAutomaticKeepAlives
2. add forceKeepChildWidget for control childWidgets's clear time. and reuse child widget
3. optimize node cache strategy.  now ,we can set keepBucket's size by keepBucketSize, to avoid big memory usage.

### CODE REVIEW

**Comment by bladeofgod** [comment]
i did some test .
SliverStaggeredGrid config :       keepBucketSize: 40,  forceKeepChildWidget: true,
1. in debug mode , show 600 more data(each has a picture) in SliverStaggeredGrid.countBuilder .  the memory will steady at 0.8G.
2. in profile mode, show 1400 more data(each has a picture) in SliverStaggeredGrid.countBuilder, the memory will steady at 554mb.

I think it's pretty well.  :)

**Comment by T-moz** [comment]
I use your fork in my project, and it works.
Thanks

**Comment by bladeofgod** [comment]
> I use your fork in my project, and it works.
> Thanks

Glade to help. :)

**Comment by rmControls** [comment]
Can you give me an example code... I used your fork , but unfortunately I didn't noticed any improvement.

**Comment by krupal4** [comment]
it this solution of following "images re rendering" problem?

https://github.com/letsar/flutter_staggered_grid_view/assets/70818026/98009871-de55-4b99-bf58-8d3e602f35d2

**Pull request closed without merging**
